name: Deploying an app
on:
    workflow_dispatch:
    push:
        branches: [ "dev" ]
jobs:
    dev:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
            DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_TOKEN }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            AWS_DEFAULT_REGION: us-east-1
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login Docker
              run: echo {{ DOCKER_PASSWORD }} | docker login -u ujwalbudha --password-stdin
            
            - name: Build docker image drom Dockerfile
              run: docker build -t ujwalbudha/myrepo-001 .