name: Deploying an app
on:
    workflow_dispatch:
    push:
        branches: [ "dev" , "main"]
jobs:
    dev:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
            AWS_DEFAULT_REGION: us-east-1
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Install AWS CLI
              run: |
                sudo apt-get update
                sudo apt-get install -y awscli

            - name: login aws cli
              run: |
               aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "${{ secrets.DOCKER_PASSWORD }}".dkr.ecr.us-east-1.amazonaws.com

            # - name: Install Docker Compose
            #   run: |
            #     DOCKER_COMPOSE_VERSION=1.29.2
            #     sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            #     sudo chmod +x /usr/local/bin/docker-compose
            #     docker-compose --version

            - name: Login Docker
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ujwalbudha --password-stdin

            # - name: Install ngrok
            #   run: |
            #     sudo apt update
            #     curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
            #     # sudo ngrok authtoken "${{ secrets.ngrok_token }}"
            #     ngrok authtoken "3NN5FPD2nLwiumBBUxRaQ_85W99134YGAKdAuHJkWkr"
      
            # - name: Run Docker-Compose
            #   run: docker-compose up -d

            # - name: Start ngrok Tunnel
            #   run: |
            #     ngrok http 8081 &

            - name: Build Docker Image
              run: |
                docker build -t ujwal.budha .

            - name: Tag Docker Image
              run: |
               docker tag ujwal.budha:latest "${{ secrets.aws_user_id }}".dkr.ecr.us-east-1.amazonaws.com/testujwal001:latest

            - name: Upload the docker image to ECR
              run: |
               docker push "${{ secrets.aws_user_id }}".dkr.ecr.us-east-1.amazonaws.com/testujwal001:latest
